// 이름 규칙 제안 event_prefix_contents
// ex.
const eventBusType = {
	RENEW_GROUP_LIST: 'RENEW_GROUP_LIST',
	RENEW_USER_LIST: 'RENEW_USER_LIST',
	CLICK_GROUP_TABLE_ROW: 'CLICK_GROUP_TABLE_ROW',
	// USER_SETTINGS_GROUP_SAVE: "USER_SETTINGS_GROUP_SAVE",
	SAVE_GROUP: 'SAVE_GROUP',
	CLICK_USER_TABLE_ROW: 'CLICK_USER_TABLE_ROW',
	// USER_SETTINGS_USER_SAVE: "USER_SETTINGS_USER_SAVE",
	SAVE_USER: 'SAVE_USER',
	RELOAD_CALL_1MIN: 'RELOAD_CALL_1MIN',
	RELOAD_CALL_25SECS: 'RELOAD_CALL_25SECS',
	AI_CHART_CLICK: 'AI_CHART_CLICK', // aichart 클릭 이벤트
	// USER_SETTINGS_DELETE: "USER_SETTINGS_DELETE",
	DELETE_USER: 'DELETE_USER',
	HTTP_ERROR_MSG: 'HTTP_ERROR_MSG', // api 통신 오류 이벤트 알림
	SPREAD_RE_CALL: 'SPREAD_RE_CALL', // 토큰 교체 됬다는 알림
};

export default eventBusType;
