const menuUtil = {
	menuList: [
		{
			children: [
				{
					children: [],
					name: 'Overview',
					icon: null,
					id: 12,
					position: 0,
					to: 'overview',
				},
				{
					children: [],
					name: 'AnomalyDetection',
					icon: null,
					id: 10,
					position: 1,
					to: 'anomalyDetection',
				},
				{
					children: [],
					name: 'LoadPrediction',
					icon: null,
					id: 11,
					position: 2,
					to: 'loadPrediction',
				},
				{
					children: [],
					name: 'Trend Chart',
					icon: null,
					id: 13,
					position: 3,
					to: 'trendChart',
				},
			],
			name: 'RealTime',
			icon: 'RealTime',
			id: 2,
			position: 0,
			to: null,
		},
		{
			children: [
				{
					children: [],
					name: 'Document',
					icon: null,
					id: 56,
					position: 0,
					to: 'documentDashboard',
				},
			],
			name: 'Dashboard',
			icon: 'Dashboard',
			id: 5,
			position: 1,
			to: null,
		},
		{
			children: [
				{
					children: [],
					name: 'PerformanceTrendAnalysis',
					icon: null,
					id: 16,
					position: 0,
					to: 'performanceTrendAnalysis',
				},
				{
					children: [],
					name: 'LongTermLoadForecast',
					icon: null,
					id: 17,
					position: 1,
					to: 'longTermLoadForecast',
				},
				{
					children: [],
					name: 'AnomalyTransactionDetection',
					icon: null,
					id: 18,
					position: 2,
					to: 'anomalyTransactionDetection',
				},
				{
					children: [],
					name: 'LoadPatternAnalysis',
					icon: null,
					id: 21,
					position: 3,
					to: 'loadPatternAnalysis',
				},
				{
					children: [],
					name: 'AlarmOccurrenceHistory',
					icon: null,
					id: 19,
					position: 4,
					to: 'alarmOccurrenceHistory',
				},
			],
			name: 'PerformanceAnalysis',
			icon: 'PerformanceAnalysis',
			id: 3,
			position: 2,
			to: null,
		},
		{
			children: [
				{
					children: [],
					name: 'SystemConfigSetting',
					icon: null,
					id: 55,
					position: 0,
					to: 'systemConfigSetting',
				},
				{
					children: [],
					name: 'LearningSetting',
					icon: null,
					id: 40,
					position: 1,
					to: 'learningSetting',
				},
				{
					children: [],
					name: 'TransactionLearningSetting',
					icon: null,
					id: 41,
					position: 2,
					to: 'transactionLearningSetting',
				},
				{
					children: [],
					name: 'ServiceSetting',
					icon: null,
					id: 42,
					position: 3,
					to: 'serviceSetting',
				},
				{
					children: [],
					name: 'BusinessCalendarSetting',
					icon: null,
					id: 43,
					position: 4,
					to: 'businessCalendarSetting',
				},
				{
					children: [],
					name: 'ObstacleHistoryManagement',
					icon: null,
					id: 44,
					position: 5,
					to: 'obstacleHistoryManagement',
				},
				{
					children: [],
					name: 'MetricSetting',
					icon: null,
					id: 45,
					position: 6,
					to: 'metricSetting',
				},
				{
					children: [],
					name: 'UserSetting',
					icon: null,
					id: 46,
					position: 7,
					to: 'userSetting',
				},
				{
					children: [],
					name: 'UserGroupSetting',
					icon: null,
					id: 47,
					position: 8,
					to: 'userGroupSetting',
				},
				{
					children: [],
					name: 'MenuAndPermissionManagement',
					icon: null,
					id: 48,
					position: 9,
					to: 'menuAndPermissionManagement',
				},
				{
					children: [],
					name: 'LoginHistory',
					icon: null,
					id: 49,
					position: 10,
					to: 'loginHistory',
				},
				{
					children: [],
					name: 'SendHistory',
					icon: null,
					id: 50,
					position: 11,
					to: 'sendHistory',
				},
				{
					children: [],
					name: 'AlertSetting',
					icon: null,
					id: 51,
					position: 12,
					to: 'alertSetting',
				},
			],
			name: 'Setting',
			icon: 'Setting',
			id: 4,
			position: 3,
			to: null,
		},
		// {
		// 	children: [
		// 		{
		// 			children: [],
		// 			name: 'Document',
		// 			icon: null,
		// 			id: 56,
		// 			position: 0,
		// 			to: 'documentDashboard',
		// 		},
		// 	],
		// 	name: 'Dashboard',
		// 	icon: 'Dashboard',
		// 	id: 5,
		// 	position: 1,
		// 	to: null,
		// },
	],
};

export default menuUtil;
